name: Install Clang
description: Install Clang.

inputs:
  clang_version:
    description: The version of Clang.
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Clang
      if: runner.os == 'Linux'
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ inputs.clang_version }}
